services:
  - type: web
    name: capstone-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://capstone-backend-sdbp.onrender.com 